version: "3.9"
services:
  worker:
    build: .
    environment:
      TG_BOT_TOKEN:
      APP_ID:
      API_HASH:
      CHANNEL_ID:
      OWNER_ID:
      DB_URI:
      FORCE_SUB_CHANNEL:
      TG_BOT_WORKERS:
      START_MSG:


